conditioning:
  method: MAP
  params:
    scale: 1

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: denoise
    type: denoise
    in_shape: !!python/tuple [1, 3, 256, 256]
  
  noise: 
    name: gaussian
    sigma: 0.5
