conditioning:
  method: MAP
  params:
    scale: 1

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: inpainting
    in_shape: !!python/tuple [1, 3, 256, 256]

    # choose from inp_lolcat, inp_lorem, inp_square
    type: inp_lorem

  # mask_opt:
  #   mask_type: random
  #   # mask_len_range: !!python/tuple [128, 129]  # for box
  #   mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
  #   image_size: 256
  
  noise: 
    name: gaussian
    sigma: 0.05